#!/usr/bin/env node
/**
 * index-project.js
 * Off-Thread Pre-Processing Indexer for TechnicalReporter agent.
 *
 * Usage:
 *   node .github/tools/index-project.js --path="<project_root>" --skills="java21,springboot3"
 *
 * Output:
 *   <project_root>/.migration-index.json
 *
 * The output is a dictionary keyed by forward-slash relative file path.
 * Each entry is an array of candidate hits:
 *   {
 *     skill, rule, line,
 *     hint,        // short one-line instruction — replaces loading the full skill rule text
 *     complex,     // true => full-class read + skill rule detail still required (see agent Step 4)
 *     context,     // pre-extracted "lineNo: text" snippet around the hit; null when complex
 *     auto,        // true => current/replacement below were deterministically generated by this script
 *     current, replacement  // only present when auto === true
 *   }
 *
 * Patterns sourced from:
 *   .github/skills/technical-reporter-rules-extractor/SKILL.md
 *
 * Zero external dependencies — uses only Node.js built-in modules.
 * Requires Node.js >= 12.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Pattern registry — mirrors the Built-In Combined Grep Index in
// technical-reporter-rules-extractor/SKILL.md
//
// Patterns are split into two groups per skill:
//   LINE_PATTERNS    — single-line regexes; matched against each line string.
//   CONTENT_PATTERNS — multi-line regexes; matched against full file content
//                      via exec() loop; line numbers are computed from offset.
//
// Every pattern also carries:
//   hint     — short instruction the agent can act on without loading the
//              full skill rule text (Lazy Skill Rule Loading).
//   complex  — true for the "Full-class read" / "Non-contiguous edits" rules
//              already called out in the agent's override table (1, 9, 21,
//              22, 24 java21; 11, 15, 19 springboot3). These still require a
//              full-class `read_file` and the detailed skill text — no
//              context/auto-fix is computed for them.
//   radius   — context-window half-size (lines) used to pre-extract `context`
//              for non-complex hits, replacing the batched read_file calls.
//
// No regex carries a /g flag here — statefulness is handled explicitly where
// needed (exec loops use locally-created regex objects).
// ---------------------------------------------------------------------------
const REGISTRY = {
  java21: {
    LINE_PATTERNS: [
      { rule: 2,  regex: /\bextends\b/, hint: 'Fixed, known subtype set — consider sealed class hierarchy with permits.', complex: false, radius: 10 },
      { rule: 7,  regex: /new\s+HashMap<|new\s+ArrayList<|new\s+LinkedHashMap</, hint: 'Use var for the local variable — type is obvious from this initializer.', complex: false, radius: 2 },
      // Negative lookbehind skips import-only lines (e.g. `import java.util.concurrent.ExecutorService;`)
      { rule: 9,  regex: /Executors\.\w+ThreadPool\b|Executors\.newSingleThread(?:Executor|ScheduledExecutor)\b|new\s+Thread\s*\(|(?<!import\s\S+\.)(?:ExecutorService|ThreadPoolExecutor)\b/, hint: 'Fixed thread pool / raw Thread for I/O-bound work — replace with virtual threads.', complex: true },
      { rule: 10, regex: /\.get\(0\)|\.getFirst\(\)|\.getLast\(\)/, hint: '.get(0) / .get(size-1) → list.getFirst() / list.getLast() (SequencedCollection).', complex: false, radius: 2 },
      { rule: 11, regex: /\.trim\(\)/, hint: '.trim() → .strip() (Unicode-aware).', complex: false, radius: 1 },
      // Rule 15 — Stream API: Collectors.toList() → Stream.toList() (renumbered; was mistagged rule 13)
      { rule: 15, regex: /Collectors\.toList\(\)/, hint: 'Collectors.toList() → Stream.toList() (Java 16+, unmodifiable).', complex: false, radius: 2 },
      // Rule 13 — Collection Factory Methods (renumbered; was mistagged rule 15)
      { rule: 13, regex: /Collections\.unmodifiable(?:List|Set|Map)\(/, hint: 'Mutable collection + Collections.unmodifiableX(...) → List.of/Map.of/Set.of factory method.', complex: false, radius: 6 },
      { rule: 16, regex: /Thread\.stop|SecurityManager|finalize\s*\(\s*\)/, hint: 'Removed/deprecated API (Thread.stop, SecurityManager, finalize) — see removal table for the replacement.', complex: false, radius: 8 },
      { rule: 18, regex: /new\s+Comparator|new\s+Runnable|new\s+Callable/, hint: 'Anonymous class implementing a functional interface → lambda or method reference.', complex: false, radius: 8 },
      // Rule 19 — Local Static Members: static nested class/interface/enum candidates
      { rule: 19, regex: /\bstatic\s+(?:class|interface|enum)\s+\w/, hint: 'Static nested type used only by one method — could be declared locally inside it.', complex: false, radius: 5 },
      // Rule 20 — Module System: internal sun.* / com.sun.* API usage
      { rule: 20, regex: /import\s+(?:sun|com\.sun)\.\w/, hint: 'Internal sun.*/com.sun.* API — replace with a supported public API (JPMS compliance).', complex: false, radius: 1 },
      // Rule 21 — Java Time API: matches both fully-qualified and standalone legacy date/time types
      { rule: 21, regex: /\b(?:java\.util\.)?(?:Date|Calendar)\b|\b(?:SimpleDateFormat|DateFormat)\b/, hint: 'Legacy java.util.Date/Calendar/SimpleDateFormat — migrate to java.time (JSR-310).', complex: true },
      // Rule 22 — Modern HTTP Client: legacy HttpURLConnection usage
      { rule: 22, regex: /HttpURLConnection\b|\.openConnection\(\)/, hint: 'Legacy HttpURLConnection — migrate to java.net.http.HttpClient/HttpRequest.', complex: true },
      // Rule 23 — Modern NIO: legacy file I/O stream constructors
      { rule: 23, regex: /new\s+(?:FileReader|FileWriter|BufferedReader|BufferedWriter)\s*\(/, hint: 'Legacy stream I/O constructor → java.nio.file.Files (readString/writeString).', complex: false, radius: 8 },
      // Rule 24 — DTO Record Conversion: classes named *DTO or *Dto (camelCase)
      { rule: 24, regex: /\bclass\s+\w+(?:DTO|Dto)\b/, hint: 'Immutable data carrier named *DTO/*Dto — convert to a record.', complex: true },
    ],
    CONTENT_PATTERNS: [
      // Rule 1 — Records: public final class ... { ... private final
      { rule: 1,  source: 'public\\s+final\\s+class\\s+\\w[\\s\\S]*?private\\s+final', hint: 'Immutable data-carrier class — convert to a record.', complex: true },
      // Rule 3 — instanceof with explicit cast on next line
      { rule: 3,  source: 'instanceof\\s+[A-Z]\\w+\\)\\s*\\{[\\s\\S]*?[A-Z]\\w+\\s+\\w+\\s*=\\s*\\(', hint: 'instanceof + explicit cast on next line → pattern variable (if (obj instanceof T t)).', complex: false, radius: 4 },
      // Rule 4 — instanceof in if/else-if chains
      { rule: 4,  source: 'instanceof[\\s\\S]*?else\\s+if', hint: 'Chain of instanceof/else-if on the same variable → switch pattern matching.', complex: false, radius: 10 },
      // Rule 5 — switch with break assigning a variable
      { rule: 5,  source: 'switch\\s*\\([\\s\\S]*?\\)\\s*\\{[\\s\\S]*?break;', hint: 'switch statement assigning/returning a value → arrow-syntax switch expression.', complex: false, radius: 10 },
      // Rule 6 — multi-line string concatenation
      { rule: 6,  source: '\\+\\s*\\n\\s*"|"""', hint: 'Multiline string concatenation / \\n-escaped string → text block ("""...""").', complex: false, radius: 6 },
      // Rule 17 — try/finally with .close()
      { rule: 17, source: '}\\s*finally[\\s\\S]*?\\.close\\(\\)', hint: 'finally block closing a resource → try-with-resources.', complex: false, radius: 8 },
      // Rule 24 — DTO Record Conversion: dto/vo/model/payload/request/response packages; full-class read required at inspection time
      { rule: 24, source: 'package\\s+[\\w.]+\\.(?:dto|vo|model|payload|request|response)\\s*;', hint: 'Immutable data-carrier class — convert to a record.', complex: true },
    ],
  },
  springboot3: {
    LINE_PATTERNS: [
      { rule: 3,  regex: /import\s+javax\./, hint: 'javax.* import → jakarta.* (namespace rename only).', complex: false, radius: 0 },
      { rule: 4,  regex: /WebSecurityConfigurerAdapter|antMatchers|mvcMatchers|authorizeRequests\s*\(\s*\)/, hint: 'WebSecurityConfigurerAdapter/antMatchers/authorizeRequests → SecurityFilterChain bean + requestMatchers/authorizeHttpRequests.', complex: false, radius: 10 },
      { rule: 5,  regex: /\.getOne\s*\(/, hint: 'repository.getOne(id) → repository.getReferenceById(id).', complex: false, radius: 2 },
      { rule: 6,  regex: /HttpMethod\.valueOf/, hint: 'HttpMethod enum comparison (==) → .equals()/.matches(); HttpMethod is now an interface.', complex: false, radius: 3 },
      { rule: 9,  regex: /JobBuilderFactory|StepBuilderFactory/, hint: 'JobBuilderFactory/StepBuilderFactory → new JobBuilder/StepBuilder(name, jobRepository, ...).', complex: false, radius: 10 },
      { rule: 12, regex: /@TypeDef|@Type\s*\(\s*type|GenerationType\.AUTO/, hint: '@TypeDef/@Type(type=) → @JdbcTypeCode(SqlTypes.X); GenerationType.AUTO → IDENTITY for auto-increment columns.', complex: false, radius: 4 },
      // Rule 15 — Third-Party Compatibility: Springfox usage in Java source needs full annotation-mapping judgment
      { rule: 15, regex: /springfox/, hint: 'Springfox usage — migrate to Springdoc OpenAPI (see annotation mapping table).', complex: true },
      // Rule 6  — Spring MVC: removed PathMatchingConfigurationAdapter
      { rule: 6,  regex: /PathMatchingConfigurationAdapter/, hint: 'PathMatchingConfigurationAdapter removed — use WebMvcConfigurer directly.', complex: false, radius: 3 },
      // Rule 11 — Removed APIs: RestTemplate still works but RestClient is preferred in Spring 6
      { rule: 11, regex: /\bRestTemplate\b/, hint: 'RestTemplate field/usage — RestClient preferred in Spring 6 (per call-site).', complex: true },
      // Rule 13 — Misc: @Timed on controllers requires explicit ObservationRegistry in Boot 3
      { rule: 13, regex: /@Timed\b/, hint: '@Timed on @RestController now needs an explicit ObservationRegistry/TimedAspect bean.', complex: false, radius: 3 },
      // Rule 17 — Legacy Servlet: HttpServlet subclasses should become @Controller
      { rule: 17, regex: /extends\s+HttpServlet\b|implements\s+(?:Controller|HttpRequestHandler)\b/, hint: 'HttpServlet subclass → @Controller with @RequestMapping methods.', complex: false, radius: 10 },
      // Rule 18 — Legacy JDBC DAO: JdbcDaoSupport should be replaced with JdbcTemplate injection
      { rule: 18, regex: /extends\s+(?:JdbcDaoSupport|HibernateDaoSupport|SqlMapClientDaoSupport)\b/, hint: 'JdbcDaoSupport/HibernateDaoSupport → inject JdbcTemplate/EntityManager directly instead of extending.', complex: false, radius: 10 },
    ],
    CONTENT_PATTERNS: [],
  },
};

// Config and build file patterns (springboot3 only) — all single-line safe
const SPRINGBOOT3_CONFIG_PATTERNS = [
  { rule: 1,  regex: /<java\.version>[0-9]|sourceCompatibility\s*=\s*['"]?[0-9]/, hint: 'Java version < 17 in pom.xml/build.gradle — bump to 17.', complex: false, radius: 2 },
  { rule: 2,  regex: /spring-boot.*2\./, hint: 'Spring Boot parent/plugin version 2.x → 3.2.x/3.3.x.', complex: false, radius: 2 },
  // Rule 15 — build-file dependency coordinate swap is a plain version/artifact bump (unlike the annotation usage above)
  { rule: 15, regex: /springfox/, hint: 'springfox dependency → org.springdoc:springdoc-openapi-starter-webmvc-ui:2.x.', complex: false, radius: 2 },
  { rule: 8,  regex: /spring\.redis\.|spring\.elasticsearch\.rest|logging\.file=|logging\.path=|datasource\.initialization-mode|server\.max-http-header-size|spring\.mvc\.pathmatch\.use-suffix-pattern/, hint: 'Renamed/removed application.properties key — see key-rename table.', complex: false, radius: 1 },
  { rule: 13, regex: /spring\.metrics\./, hint: 'spring.metrics.* property → management.metrics.*.', complex: false, radius: 1 },
  { rule: 14, regex: /allow-circular-references\s*=\s*true/, hint: 'Circular-reference workaround flag present — temporary only, do not leave in production.', complex: false, radius: 1 },
  // Rule 19 — XML config files: Spring MVC namespace or web.xml descriptor (needs the file-creation flow, not a simple swap)
  { rule: 19, regex: /xmlns:(?:mvc|beans)\s*=\s*['"]http:\/\/www\.springframework\.org\/schema|<web-app\b/, hint: 'XML servlet/MVC config — migrate to a Java @Configuration class (Rule 19 file-creation flow).', complex: true },
];

// ---------------------------------------------------------------------------
// CLI argument parsing
// ---------------------------------------------------------------------------
function parseArgs(argv) {
  const args = {};
  for (const arg of argv.slice(2)) {
    const eq  = arg.indexOf('=');
    const key = arg.slice(2, eq);          // strip leading --
    args[key] = eq === -1 ? true : arg.slice(eq + 1);
  }
  return args;
}

// ---------------------------------------------------------------------------
// File-type predicates (shared by discoverFiles and scanFile)
// ---------------------------------------------------------------------------
const isJavaFile      = name => name.endsWith('.java');
const isConfigFile    = name => /\.(properties|ya?ml)$/.test(name);
const isBuildFile     = name => name === 'pom.xml' || name === 'build.gradle';
// Spring XML descriptors (web.xml, *-context.xml, *-servlet.xml) — excludes pom.xml
const isSpringXmlFile = name => name !== 'pom.xml' && name.endsWith('.xml');

// ---------------------------------------------------------------------------
// Zero-dependency recursive file discovery
// ---------------------------------------------------------------------------
const EXCLUDE_SEGMENTS = new Set([
  'target', 'build', '.gradle', 'out', '.git', 'node_modules', 'dist',
]);
const EXCLUDE_PATTERNS = [
  /[\\/]generated/i,
  /[\\/]protobuf[\\/]/,
  /[\\/]openapi[\\/]/,
  /[\\/]mapstruct[\\/]/,
];

function shouldExclude(absPath) {
  const parts = absPath.split(/[\\/]/);
  if (parts.some(p => EXCLUDE_SEGMENTS.has(p))) return true;
  if (EXCLUDE_PATTERNS.some(re => re.test(absPath)))  return true;
  return false;
}

function walkDir(dir, matchFn, results = []) {
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); }
  catch (_) { return results; }

  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (shouldExclude(full)) continue;
    if (entry.isDirectory()) {
      walkDir(full, matchFn, results);
    } else if (entry.isFile() && matchFn(entry.name)) {
      results.push(full);
    }
  }
  return results;
}

function discoverFiles(projectPath, activeSkills) {
  const javaRoot = path.join(projectPath, 'src', 'main', 'java');
  const scanRoot = fs.existsSync(javaRoot) ? javaRoot : projectPath;

  let files = walkDir(scanRoot, isJavaFile);

  if (activeSkills.includes('springboot3')) {
    const resourcesRoot = path.join(projectPath, 'src', 'main', 'resources');
    if (fs.existsSync(resourcesRoot)) {
      files = files.concat(walkDir(resourcesRoot, isConfigFile));
      files = files.concat(walkDir(resourcesRoot, isSpringXmlFile));
    }
    const webAppRoot = path.join(projectPath, 'src', 'main', 'webapp');
    if (fs.existsSync(webAppRoot)) {
      files = files.concat(walkDir(webAppRoot, isSpringXmlFile));
    }
    files = files.concat(walkDir(projectPath, isBuildFile).filter(f => {
      // Only top-level pom.xml / build.gradle
      return path.dirname(f) === projectPath;
    }));
  }

  return [...new Set(files)];
}

// ---------------------------------------------------------------------------
// Compute line number (1-based) from a character offset within content
// ---------------------------------------------------------------------------
function offsetToLine(content, offset) {
  let line = 1;
  for (let i = 0; i < offset; i++) {
    if (content[i] === '\n') line++;
  }
  return line;
}

// ---------------------------------------------------------------------------
// Deterministic auto-fixers — only for transforms with zero semantic
// ambiguity (plain namespace/token rename). Anything requiring judgment
// (e.g. Springfox attribute renaming) is intentionally left unfixed so a
// wrong replacement is never silently proposed.
// ---------------------------------------------------------------------------
const AUTO_FIXERS = {
  'springboot3:3':  (line) => /^\s*import\s+javax\./.test(line) ? line.replace(/\bjavax\./, 'jakarta.') : null,
  'java21:11':      (line) => line.includes('.trim()') ? line.replace(/\.trim\(\)/g, '.strip()') : null,
};

// Builds a bounded, line-numbered context snippet around a hit — this is
// what lets the agent skip the batched read_file calls for non-complex rules.
function buildContext(lines, lineNo, radius) {
  const start = Math.max(1, lineNo - radius);
  const end   = Math.min(lines.length, lineNo + radius);
  const slice = [];
  for (let i = start; i <= end; i++) slice.push(`${i}: ${lines[i - 1]}`);
  return slice.join('\n');
}

// Apply an array of single-line patterns against pre-split lines, enriching
// each hit with hint/complex/context/auto per the pattern's own metadata.
function applyLinePatterns(patterns, lines, skill, addHit) {
  for (const { rule, regex, hint, complex, radius } of patterns) {
    lines.forEach((ln, idx) => {
      if (!regex.test(ln)) return;
      const lineNo = idx + 1;
      const entry  = { hint, complex };
      if (!complex) {
        entry.context = buildContext(lines, lineNo, radius == null ? 8 : radius);
        const fixer = AUTO_FIXERS[`${skill}:${rule}`];
        const fixed = fixer ? fixer(ln) : null;
        if (fixed !== null) {
          entry.auto        = true;
          entry.current     = ln.trim();
          entry.replacement = fixed.trim();
        }
      } else {
        entry.context = null;
      }
      addHit(skill, rule, lineNo, entry);
    });
  }
}

// ---------------------------------------------------------------------------
// Single-file scanner — returns array of enriched hits (see header docblock)
// ---------------------------------------------------------------------------
async function scanFile(filePath, activeSkills) {
  let content;
  try { content = await fs.promises.readFile(filePath, 'utf8'); }
  catch (_) { return []; }

  const lines   = content.split('\n');
  const hits    = [];
  const seen    = new Set(); // deduplicate (skill, rule, line) triples

  function addHit(skill, rule, lineNo, extra) {
    const key = `${skill}:${rule}:${lineNo}`;
    if (!seen.has(key)) { seen.add(key); hits.push({ skill, rule, line: lineNo, ...extra }); }
  }

  const isJava   = isJavaFile(path.basename(filePath));
  const isConfig = isConfigFile(path.basename(filePath));
  const isBuild  = isBuildFile(path.basename(filePath));

  for (const skill of activeSkills) {
    const { LINE_PATTERNS = [], CONTENT_PATTERNS = [] } = REGISTRY[skill] || {};

    // --- Java file: line-by-line patterns then multi-line content patterns ---
    if (isJava) {
      applyLinePatterns(LINE_PATTERNS, lines, skill, addHit);

      for (const { rule, source, hint, complex, radius } of CONTENT_PATTERNS) {
        const re = new RegExp(source, 'g');   // fresh stateful regex each time
        let m;
        while ((m = re.exec(content)) !== null) {
          const lineNo = offsetToLine(content, m.index);
          addHit(skill, rule, lineNo, complex ? { hint, complex, context: null } : { hint, complex, context: buildContext(lines, lineNo, radius == null ? 8 : radius) });
          // Prevent infinite loop on zero-length matches
          if (m.index === re.lastIndex) re.lastIndex++;
        }
      }
    }

    // --- Config / build / Spring XML file patterns (springboot3 only, all single-line) ---
    const isSpringXml = isSpringXmlFile(path.basename(filePath));
    if (skill === 'springboot3' && (isConfig || isBuild || isSpringXml)) {
      applyLinePatterns(SPRINGBOOT3_CONFIG_PATTERNS, lines, skill, addHit);
    }
  }

  return hits;
}

// ---------------------------------------------------------------------------
// Lightweight concurrency-limited async map — no external deps (no p-limit,
// no worker_threads: regex scanning is cheap, the disk I/O across hundreds of
// files was the actual sequential bottleneck). A small fixed pool of workers
// pulls from a shared index, so disk reads overlap instead of queuing.
// ---------------------------------------------------------------------------
async function mapWithConcurrency(items, limit, fn) {
  let next = 0;
  async function worker() {
    while (next < items.length) {
      const i = next++;
      await fn(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main() {
  const args        = parseArgs(process.argv);
  const projectPath = path.resolve(args.path || '.');
  const skillsArg   = String(args.skills || 'java21,springboot3')
    .split(',')
    .map(s => s.trim())
    .filter(Boolean);
  const activeSkills = skillsArg.filter(s => Object.prototype.hasOwnProperty.call(REGISTRY, s));

  if (!fs.existsSync(projectPath)) {
    console.error(`ERROR: project path not found: ${projectPath}`);
    process.exit(1);
  }
  if (activeSkills.length === 0) {
    console.error(`ERROR: no valid skills found in --skills="${args.skills}". Valid values: ${Object.keys(REGISTRY).join(', ')}`);
    process.exit(1);
  }

  console.log(`Indexing: ${projectPath}`);
  console.log(`Skills:   ${activeSkills.join(', ')}`);

  const files    = discoverFiles(projectPath, activeSkills);
  const indexMap = {};
  let   hitFiles = 0;

  // Concurrency cap balances parallel disk I/O against file-descriptor limits
  // on very large trees; 16 is a conservative default for hundreds of files.
  const CONCURRENCY = 16;
  await mapWithConcurrency(files, CONCURRENCY, async (file) => {
    const hits = await scanFile(file, activeSkills);
    if (hits.length > 0) {
      // Bug 3 fix: normalize to forward slashes regardless of OS
      const relPath     = path.relative(projectPath, file).replace(/\\/g, '/');
      indexMap[relPath] = hits;
      hitFiles++;
    }
  });

  const outputPath = path.join(projectPath, '.migration-index.json');
  fs.writeFileSync(outputPath, JSON.stringify(indexMap, null, 2), 'utf8');

  console.log(`Done. ${hitFiles} files with candidates out of ${files.length} scanned.`);
  console.log(`Index written to: ${outputPath}`);
}

main().catch((err) => {
  console.error(`ERROR: ${err.stack || err.message}`);
  process.exit(1);
});

